name: get-literature-zotero
on:
  schedule:
    - cron:  '0 12 * * 5'
    
jobs:
  zotero-literature:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: update 
        run: |
          curl -o _data/phantom_literature.json "https://api.zotero.org/groups/2900833/items/top?key=eTYEyPZvup4cRMnUrMkSPkAS&format=json"
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
            token: ${{ secrets.GITHUB_TOKEN }}
            commit-message: "[BOT] Update phantom literature"
            title: "[BOT] Update phantom literature"
            body: |
              - This is an automated pull request.
            branch: update-data
